apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ganesh
  template:
    metadata:
      name: my-pod12
      labels:
        app: ganesh
    spec:
      containers:
      - name : my-cont1
        image: httpd
        ports:
        - containerPort: 8080
