apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort # to change service type make changes only in (type:LoadBalancer)
  ports:
  - name : http
    protocol: TCP
    port: 80
